apiVersion: v1
kind: Service
metadata:
  name: postgres-loadbalancer
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}

